apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20230817203625.0.0+build.190d139
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20230817203625.0.0+build.190d139
  releaseNotes: |
    Release v20230817203625.0.0+build.190d139 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/where-for-dinner-search-my-apps-bundle@sha256:5d751e4e127d5fa466d8bde45779da9f2d2334967edbd8fd1647f0f3bfdf3893
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

