apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20231121184804.0.0+build.9bdc03b
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20231121184804.0.0+build.9bdc03b
  releaseNotes: |
    Release v20231121184804.0.0+build.9bdc03b of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/where-for-dinner-search-my-apps-bundle@sha256:2628f29e3e190397cdabc071e43e9a93628ef9763f222ddefdf5653f161d7cc8
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

