apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tanzu-java-web-app-carvel2.my-apps.tap.20230817132535.0.0+build.ac352a6
spec:
  refName: tanzu-java-web-app-carvel2.my-apps.tap
  version: 20230817132535.0.0+build.ac352a6
  releaseNotes: |
    Release v20230817132535.0.0+build.ac352a6 of package tanzu-java-web-app-carvel2.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/tanzu-java-web-app-carvel2-my-apps-bundle@sha256:1722590b3fbb13634f3f7af81ab93be05b0c5e2b7564cd442986146417f4b5ec
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

