apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-ui.my-apps.tap.20230828073548.0.0+build.190d139
spec:
  refName: where-for-dinner-ui.my-apps.tap
  version: 20230828073548.0.0+build.190d139
  releaseNotes: |
    Release v20230828073548.0.0+build.190d139 of package where-for-dinner-ui.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/where-for-dinner-ui-my-apps-bundle@sha256:9419dba96d240e16770cb47db5d5417bf99ab766e76018ae50cca9a5d572d973
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

