apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20231206200542.0.0+build.bfa0ffc
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20231206200542.0.0+build.bfa0ffc
  releaseNotes: |
    Release v20231206200542.0.0+build.bfa0ffc of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-my-apps-bundle@sha256:2fbce4132da99171be81247bbca37b38335e9c4126384e2c657662f8c772d03f
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

