apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20231123080146.0.0+build.9d1714d
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20231123080146.0.0+build.9d1714d
  releaseNotes: |
    Release v20231123080146.0.0+build.9d1714d of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/where-for-dinner-my-apps-bundle@sha256:6ffeb438b408d26e374e72fc60f86664b997d8f3854ffd8287194df7f80cf32f
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

