apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20231211135510.0.0+build.0e54ade
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20231211135510.0.0+build.0e54ade
  releaseNotes: |
    Release v20231211135510.0.0+build.0e54ade of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-my-apps-bundle@sha256:c56002bcbf90e3732c1abc99e903935e327609695c5034435debab7b8be40bd2
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

