apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20231206195811.0.0+build.7da8849
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20231206195811.0.0+build.7da8849
  releaseNotes: |
    Release v20231206195811.0.0+build.7da8849 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-my-apps-bundle@sha256:594b1fff080d9a2a75749e9598d26e2e309f72fc656824866f38d3509ee7c92d
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

