apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20231207190852.0.0+build.cae84db
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20231207190852.0.0+build.cae84db
  releaseNotes: |
    Release v20231207190852.0.0+build.cae84db of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-my-apps-bundle@sha256:cd3c02f290507270228f6c112aaa4b23e4c1ef76da5b860bcc69c545818070dc
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

