apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20231204155142.0.0+build.5a678ea
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20231204155142.0.0+build.5a678ea
  releaseNotes: |
    Release v20231204155142.0.0+build.5a678ea of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-my-apps-bundle@sha256:87b1d66a3cd5385521859b79c658a19f3cb6cdf9b292f95afd1273ed6fc15f6c
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

