apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20231204221607.0.0+build.5161977
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20231204221607.0.0+build.5161977
  releaseNotes: |
    Release v20231204221607.0.0+build.5161977 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-my-apps-bundle@sha256:81ecc0b5f7f74fba61647900b088f268eb28f498d637ad978cd8271cf979b393
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

