apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20230828184441.0.0+build.190d139
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20230828184441.0.0+build.190d139
  releaseNotes: |
    Release v20230828184441.0.0+build.190d139 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/where-for-dinner-my-apps-bundle@sha256:df9addbf44ff4255dbc9d55112a4ec4bc8db67b767ae35f2d79f3988a3eee5ac
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

