apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240322141514.0.0+build.10b46c5
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240322141514.0.0+build.10b46c5
  releaseNotes: |
    Release v20240322141514.0.0+build.10b46c5 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-my-apps-bundle@sha256:9aeda20690419ed0c65f392f6b28dc559a81602b3f114ca4539162641d2352f3
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

