apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240201104101.0.0+build.209d885
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240201104101.0.0+build.209d885
  releaseNotes: |
    Release v20240201104101.0.0+build.209d885 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-my-apps-bundle@sha256:033b8fc9a776cdebeba2983b7ec83ca2cd500adb1a2e98a1ff2bdbe63a357243
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

