apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240223105246.0.0+build.fe68638
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240223105246.0.0+build.fe68638
  releaseNotes: |
    Release v20240223105246.0.0+build.fe68638 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-my-apps-bundle@sha256:266ca655c251d8572dd58a0f76de426a194e3b7df616a210ee7788d939047229
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

