apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240408135839.0.0+build.d44eb58
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240408135839.0.0+build.d44eb58
  releaseNotes: |
    Release v20240408135839.0.0+build.d44eb58 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-my-apps-bundle@sha256:4a00d742ce14101e9491ccfa6e4ae85857674b6756296448723c9bebdbccb539
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

