apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240408130137.0.0+build.178fb8b
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240408130137.0.0+build.178fb8b
  releaseNotes: |
    Release v20240408130137.0.0+build.178fb8b of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-my-apps-bundle@sha256:377973187d6cbed2eddfe23f5458469353240080b5e1bbfd2aaf59750968da07
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

