apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240322130218.0.0+build.29fd54c
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240322130218.0.0+build.29fd54c
  releaseNotes: |
    Release v20240322130218.0.0+build.29fd54c of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-my-apps-bundle@sha256:51262ba00e826f3d5668fc9cbeaf28039fb36a4175f59147a453c326be292df8
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

