apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240312180815.0.0+build.acc9929
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240312180815.0.0+build.acc9929
  releaseNotes: |
    Release v20240312180815.0.0+build.acc9929 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-my-apps-bundle@sha256:3db539cfbb55fdf57692dbf4ec660fba3b15078218ec6495550ed8814e673fbf
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

