apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: where-for-dinner-api-gateway
    apps.tanzu.vmware.com/has-tests: "false"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/carvel-package-workflow: "true"
spec:
  params:
  - name: gitops_server_address
    value: https://github.com/
  - name: gitops_repository_owner
    value: ybhagwan
  - name: gitops_repository_name
    value: carvel-gitops5
  - name: gitops_ssh_secret
    value: git-ssh
  - name: gitops_server_kind
    value: github
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
      autoscaling.knative.dev/target: "200"
      autoscaling.knative.dev/maxScale: "4"
  resources:
    requests:
      memory: 500M
      cpu: 100m
    limits:
      memory: 750M
      cpu: 1500m
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples.git
      ref:
        branch: main
    subPath: where-for-dinner/where-for-dinner-api-gateway
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-search
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: where-for-dinner-search
    networking.knative.dev/visibility: cluster-local
    apps.tanzu.vmware.com/has-tests: "false"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/carvel-package-workflow: "true"
spec:
  env:
  - name: spring_profiles_active
    value: mysql
  - name: SPRING_RABBITMQ_SSL_ENABLED
    value: "true"
  params:
  - name: gitops_server_address
    value: https://github.com/
  - name: gitops_repository_owner
    value: ybhagwan
  - name: gitops_repository_name
    value: carvel-gitops5
  - name: gitops_ssh_secret
    value: git-ssh
  - name: gitops_server_kind
    value: github
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: rmq-where-for-dinner
  - name: db
    ref:
      apiVersion: v1
      kind: Secret
      name: mysql-where-for-dinner
  resources:
    requests:
      memory: 500M
      cpu: 100m
    limits:
      memory: 750M
      cpu: 1500m
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples.git
      ref:
        branch: main
    subPath: where-for-dinner/where-for-dinner-search
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-search-proc
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: where-for-dinner-search-proc
    networking.knative.dev/visibility: cluster-local
    apps.tanzu.vmware.com/has-tests: "false"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/carvel-package-workflow: "true"
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  params:
  - name: gitops_server_address
    value: https://github.com/
  - name: gitops_repository_owner
    value: ybhagwan
  - name: gitops_repository_name
    value: carvel-gitops5
  - name: gitops_ssh_secret
    value: git-ssh
  - name: gitops_server_kind
    value: github
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http
  env:
  - name: spring_profiles_active
    value: crawler,redis
  - name: SPRING_RABBITMQ_SSL_ENABLED
    value: "true"
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: rmq-where-for-dinner
  - name: redis
    ref:
      apiVersion: v1
      kind: Secret
      name: redis-where-for-dinner-redis-secret
  resources:
    requests:
      memory: 500M
      cpu: 100m
    limits:
      memory: 750M
      cpu: 1500m
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples.git
      ref:
        branch: main
    subPath: where-for-dinner/where-for-dinner-search-proc
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-notify
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: where-for-dinner-notify
    networking.knative.dev/visibility: cluster-local
    apps.tanzu.vmware.com/has-tests: "false"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/carvel-package-workflow: "true"
spec:
  env:
  - name: SPRING_RABBITMQ_SSL_ENABLED
    value: "true"
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  params:
  - name: gitops_server_address
    value: https://github.com/
  - name: gitops_repository_owner
    value: ybhagwan
  - name: gitops_repository_name
    value: carvel-gitops5
  - name: gitops_ssh_secret
    value: git-ssh
  - name: gitops_server_kind
    value: github
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: rmq-where-for-dinner
  resources:
    requests:
      memory: 500M
      cpu: 100m
    limits:
      memory: 750M
      cpu: 1500m
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples.git
      ref:
        branch: main
    subPath: where-for-dinner/where-for-dinner-notify
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-availability
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: where-for-dinner-availability
    networking.knative.dev/visibility: cluster-local
    apps.tanzu.vmware.com/has-tests: "false"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/carvel-package-workflow: "true"
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  env:
  - name: spring_profiles_active
    value: mysql
  - name: SPRING_RABBITMQ_SSL_ENABLED
    value: "true"
  params:
  - name: gitops_server_address
    value: https://github.com/
  - name: gitops_repository_owner
    value: ybhagwan
  - name: gitops_repository_name
    value: carvel-gitops5
  - name: gitops_ssh_secret
    value: git-ssh
  - name: gitops_server_kind
    value: github
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: rmq-where-for-dinner
  - name: db
    ref:
      apiVersion: v1
      kind: Secret
      name: mysql-where-for-dinner
  resources:
    requests:
      memory: 500M
      cpu: 100m
    limits:
      memory: 750M
      cpu: "1.5"
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples.git
      ref:
        branch: main
    subPath: where-for-dinner/where-for-dinner-availability
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-ui
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: where-for-dinner-ui
    networking.knative.dev/visibility: cluster-local
    apps.tanzu.vmware.com/has-tests: "false"
    apps.tanzu.vmware.com/carvel-package-workflow: "true"
spec:
  build:
    env:
    - name: BP_NODE_RUN_SCRIPTS
      value: build
    - name: BP_WEB_SERVER_ROOT
      value: dist
  params:
  - name: gitops_server_address
    value: https://github.com/
  - name: gitops_repository_owner
    value: ybhagwan
  - name: gitops_repository_name
    value: carvel-gitops5
  - name: gitops_ssh_secret
    value: git-ssh
  - name: gitops_server_kind
    value: github
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http
  resources:
    requests:
      memory: 500M
      cpu: 100m
    limits:
      memory: 750M
      cpu: 1500m
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples.git
      ref:
        branch: main
    subPath: where-for-dinner/where-for-dinner-ui
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-crawler
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: where-for-dinner-crawler
    apps.tanzu.vmware.com/has-tests: "false"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/carvel-package-workflow: "true"
spec:
  params:
  - name: gitops_server_address
    value: https://github.com/
  - name: gitops_repository_owner
    value: ybhagwan
  - name: gitops_repository_name
    value: carvel-gitops5
  - name: gitops_ssh_secret
    value: git-ssh
  - name: gitops_server_kind
    value: github
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http
  resources:
    requests:
      memory: 500M
      cpu: 100m
    limits:
      memory: 750M
      cpu: 1500m
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples.git
      ref:
        branch: main
    subPath: where-for-dinner/where-for-dinner-crawler

