apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20231206195744.0.0+build.7da8849
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20231206195744.0.0+build.7da8849
  releaseNotes: |
    Release v20231206195744.0.0+build.7da8849 of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-search-proc-my-apps-bundle@sha256:e7b51d638d680530bb6e376759ca3ccb81b63c64fe5074522b88e3810f56fc64
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
        replicas:
          type: integer
          default: 1

