apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20231122192659.0.0+build.9bdc03b
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20231122192659.0.0+build.9bdc03b
  releaseNotes: |
    Release v20231122192659.0.0+build.9bdc03b of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/where-for-dinner-search-proc-my-apps-bundle@sha256:b2be0062a28b10eddc476828f4015452aef77a753c5eeca873f9265a1aa73ff1
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

