apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20231206143033.0.0+build.503cec0
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20231206143033.0.0+build.503cec0
  releaseNotes: |
    Release v20231206143033.0.0+build.503cec0 of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-search-proc-my-apps-bundle@sha256:b792975ebabb108973aef553125dd7939f1452cda0dc317cbadef21776a9cb7c
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
        replicas:
          type: integer
          default: 1

