apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20231207144621.0.0+build.30ad694
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20231207144621.0.0+build.30ad694
  releaseNotes: |
    Release v20231207144621.0.0+build.30ad694 of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-search-proc-my-apps-bundle@sha256:7f189de4d66c491d23489a47b7e671221b18d94e45ce21161fedffa4cb627739
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
        replicas:
          type: integer
          default: 1

