apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20230828184454.0.0+build.190d139
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20230828184454.0.0+build.190d139
  releaseNotes: |
    Release v20230828184454.0.0+build.190d139 of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/where-for-dinner-search-proc-my-apps-bundle@sha256:daa40be59b84b42ea072439dba3c5b15f71aa0452e9e0f6d181b4d568b511abc
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

