apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20231206194719.0.0+build.0b55f26
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20231206194719.0.0+build.0b55f26
  releaseNotes: |
    Release v20231206194719.0.0+build.0b55f26 of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-search-proc-my-apps-bundle@sha256:1fb4bd4876ba74c0a4cf601b181fdfe24a6d990d23b26b26f3862ffd58b44bca
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
        replicas:
          type: integer
          default: 1

