apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20230817203718.0.0+build.190d139
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20230817203718.0.0+build.190d139
  releaseNotes: |
    Release v20230817203718.0.0+build.190d139 of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/where-for-dinner-search-proc-my-apps-bundle@sha256:7aaa35abe4bfa274a967a869c7f171e07e4b25368d062ebf985f989adc229b7d
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

