apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20231206164554.0.0+build.15075ed
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20231206164554.0.0+build.15075ed
  releaseNotes: |
    Release v20231206164554.0.0+build.15075ed of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-search-proc-my-apps-bundle@sha256:ab4d2e9b0bd92dc283014b838b962b8a673e9f30f9d691343166e2c92db826bb
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
        replicas:
          type: integer
          default: 1

