apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20231121184826.0.0+build.9bdc03b
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20231121184826.0.0+build.9bdc03b
  releaseNotes: |
    Release v20231121184826.0.0+build.9bdc03b of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/where-for-dinner-search-proc-my-apps-bundle@sha256:e0cc168b96cc277fe6d5d79c25d1658ae31572f84219570ad1c455bad9709ab4
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

