apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20231207190814.0.0+build.cae84db
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20231207190814.0.0+build.cae84db
  releaseNotes: |
    Release v20231207190814.0.0+build.cae84db of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-search-proc-my-apps-bundle@sha256:a11aca99b5f0743cb689e011bf01cde817522374485fad75afff6b34e26b3c1a
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
        replicas:
          type: integer
          default: 1

