apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20231211135501.0.0+build.0e54ade
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20231211135501.0.0+build.0e54ade
  releaseNotes: |
    Release v20231211135501.0.0+build.0e54ade of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-search-proc-my-apps-bundle@sha256:81e15e1798c608fe7925a991a2fe22a8287c1d691850520f222aaa6738fab26c
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
        replicas:
          type: integer
          default: 1

