apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20231206201926.0.0+build.9de53d8
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20231206201926.0.0+build.9de53d8
  releaseNotes: |
    Release v20231206201926.0.0+build.9de53d8 of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: spacesdemo1.azurecr.io/demo1/where-for-dinner-search-proc-my-apps-bundle@sha256:4d7441a83d3f1ec4f0bff04e5c8079aa030602665c23bf6d34041892c4b3c01c
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
        replicas:
          type: integer
          default: 1

