apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-availability.my-apps.tap.20231122062620.0.0+build.9bdc03b
spec:
  refName: where-for-dinner-availability.my-apps.tap
  version: 20231122062620.0.0+build.9bdc03b
  releaseNotes: |
    Release v20231122062620.0.0+build.9bdc03b of package where-for-dinner-availability.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/where-for-dinner-availability-my-apps-bundle@sha256:31f8f8490857aed64fde277df716a1b718c0819168233f7876f6594f41f920b8
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

