apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-availability.my-apps.tap.20230822045033.0.0+build.190d139
spec:
  refName: where-for-dinner-availability.my-apps.tap
  version: 20230822045033.0.0+build.190d139
  releaseNotes: |
    Release v20230822045033.0.0+build.190d139 of package where-for-dinner-availability.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/where-for-dinner-availability-my-apps-bundle@sha256:ce6b459b023abe00fd3a72f2c376c3329ca8ba7e188ca8fd8318ebb1be928ca5
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

