apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-availability.my-apps.tap.20230828184438.0.0+build.190d139
spec:
  refName: where-for-dinner-availability.my-apps.tap
  version: 20230828184438.0.0+build.190d139
  releaseNotes: |
    Release v20230828184438.0.0+build.190d139 of package where-for-dinner-availability.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/where-for-dinner-availability-my-apps-bundle@sha256:22699bccfd1f014777d676b5b6db63a8d494b1a51068257125539d36b5709fff
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

