apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tanzu-java-web-app-carvel21.my-apps.tap.20231121095256.0.0+build.ac352a6
spec:
  refName: tanzu-java-web-app-carvel21.my-apps.tap
  version: 20231121095256.0.0+build.ac352a6
  releaseNotes: |
    Release v20231121095256.0.0+build.ac352a6 of package tanzu-java-web-app-carvel21.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/tanzu-java-web-app-carvel21-my-apps-bundle@sha256:190f33896495129e6bf415c97b7fc07de844e91f418fecf0788ece1f76b9e725
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

